site_name: Solrift Token Docs

theme:
  name: material
  palette:
    primary: deep orange
    accent: orange

nav:
  - Home: index.md
  - Key Features: features/index.md
  - Why Solrift: why-solrift/index.md
  - Contribute: contribute/index.md

repo_url: https://github.com/SolRift/SolRift-Token
repo_name: SolRift-Token
